name: Notify Slack Channel on Pull Request Updates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run:  |
             echo "Installing dependencies..." 
             npm install

      - name:  Send Slack notification
        run: |
          echo "Sending Slack notification..."
          node notify.js
