name: Notify Slack Channel on Pull Request Updates

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, closed, reopened]

  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run:  |
             echo "Installing dependencies..." 
             npm install

      - name: Send Slack notification
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_ACTION: ${{ github.event.action }}
          PR_REVIEW_STATE: ${{ github.event.review.state }}
        run: |
          echo "Sending Slack notification..."
          node notify.js
