name: Notify Slack Channel on Pull Request Updates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, closed, reopened]

  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run:  |
             echo "Installing dependencies..." 
             npm install

      - name: Send Slack notification
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: |
          echo "Sending Slack notification..."
          node notify.js
